---
title: "final_starters"
author: "Yunzhe Qi"
date: "4/30/2021"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Group by positions
```{r setup, message=FALSE}
library(ISLR)
library(MASS)
library(class)
library(boot)
library(glmnet)
library(pls)
library(splines)
library(gam)
library(gbm)
library(randomForest)
library(e1071)
library(dplyr)
library(broom)
library(tidyr)
library(ggplot2)
set.seed(100)
```

# LOGISTIC REGRESSION MODEL:

```{r}
library(readr)
library(MASS)
starters = read_csv('2019-2020_ANNO_games_details_STARTER.csv')
benches = read_csv('2019-2020_ANNO_games_details_BENCH.csv')
starters = subset(starters, select = -c(COMMENT))
starters = na.omit(starters)
starters$WIN = as.numeric(starters$WIN)
starters$Home_team = as.numeric(starters$Home_team)
starters$TEAM_ABBREVIATION = toupper(starters$TEAM_ABBREVIATION)
starters$START_POSITION = toupper(starters$START_POSITION)

#
d_length = dim(starters)[1]
train_index = sample(d_length, d_length/2)
train_starter = starters[train_index,]
test_starter = starters[-train_index,]


# Position -- 8th
X_train = starters[train_index, 9:29]
X_test = starters[-train_index, 9:29]
Y_train = starters[train_index, 30]
Y_test = starters[-train_index, 30]

#
starters_numeric = starters[, 9:30]

```
```{r}
# attach(train_starter)
library(dplyr)
set.seed(1)
team = train_starter %>% group_by(START_POSITION)
# team = train_starter %>% group_by(TEAM_ABBREVIATION)

# Fit the models
lm_models = train_starter %>% 
  group_by(START_POSITION) %>%
  do(fit = glm(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data=., family = binomial(logit)))


#
my_lm <- function(df) {
    fit = glm(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data=df, family = binomial(logit))
    return(fit)
}

lm_preds = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_lm(.), newdata = test_starter))

lm_preds_train = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_lm(.), newdata = train_starter))

#
lm_error_rate_test = rep(0, 5)
for (x in 1:5) {
  lm_pred_list = lm_preds$pred[[x]]
  lm_pred = rep(0, length(lm_pred_list))
  threshold <- 0.5
  lm_pred[lm_pred_list > threshold] = 1
  lm_error_rate_test[x] = mean(lm_pred != test_starter$WIN)
}

#
lm_error_rate_train = rep(0, 5)
for (x in 1:5) {
  lm_pred_list = lm_preds_train$pred[[x]]
  lm_pred = rep(0, length(lm_pred_list))
  threshold <- 0.5
  lm_pred[lm_pred_list > threshold] = 1
  lm_error_rate_train[x] = mean(lm_pred != train_starter$WIN)
}


print(lm_models$START_POSITION)
print(lm_error_rate_train)
print(lm_error_rate_test)
```
# Random Forest model:

```{r}
#
my_rf <- function(df) {
    fit = randomForest(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data = df, mtry = 5, importance=TRUE, ntrees=25)
    return(fit)
}

rf_preds = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_rf(.), newdata = test_starter))

rf_preds_train = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_rf(.), newdata = train_starter))

#
rf_error_rate_test = rep(0, 5)
for (x in 1:5) {
  rf_pred_list = rf_preds$pred[[x]]
  rf_pred = rep(0, length(rf_pred_list))
  threshold <- 0.5
  rf_pred[rf_pred_list > threshold] = 1
  rf_error_rate_test[x] = mean(rf_pred != test_starter$WIN)
}

rf_error_rate_train = rep(0, 5)
for (x in 1:5) {
  rf_pred_list = rf_preds_train$pred[[x]]
  rf_pred = rep(0, length(rf_pred_list))
  threshold <- 0.5
  rf_pred[rf_pred_list > threshold] = 1
  rf_error_rate_train[x] = mean(rf_pred != train_starter$WIN)
}


print(lm_models$START_POSITION)
print(rf_error_rate_train)
print(rf_error_rate_test)
```


# SVM model:

```{r}
#
my_svm <- function(df) {
    fit = svm(WIN~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, kernel = "radial", data = df)
    return(fit)
}

svm_preds = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_svm(.), newdata = test_starter))

svm_preds_train = train_starter %>% 
  group_by(START_POSITION) %>%
  do(pred = predict(my_svm(.), newdata = train_starter))


#
svm_error_rate_test = rep(0, 5)
for (x in 1:5) {
  svm_pred_list = svm_preds$pred[[x]]
  svm_pred = rep(0, length(svm_pred_list))
  threshold <- 0.5
  svm_pred[svm_pred_list > threshold] = 1
  svm_error_rate_test[x] = mean(svm_pred != test_starter$WIN)
}

svm_error_rate_train = rep(0, 5)
for (x in 1:5) {
  svm_pred_list = svm_preds_train$pred[[x]]
  svm_pred = rep(0, length(svm_pred_list))
  threshold <- 0.5
  svm_pred[svm_pred_list > threshold] = 1
  svm_error_rate_train[x] = mean(svm_pred != train_starter$WIN)
}


print(lm_models$START_POSITION)
print(svm_error_rate_train)
print(svm_error_rate_test)
```


# Print the results
```{r}
df_results_train <- data.frame(svm = svm_error_rate_train, RF = rf_error_rate_train, lm=lm_error_rate_train)
row.names(df_results_train) <- lm_models$START_POSITION

df_results_test <- data.frame(svm = svm_error_rate_test, RF = rf_error_rate_test, lm=lm_error_rate_test)
row.names(df_results_test) <- lm_models$START_POSITION

df_results_train
df_results_test
barplot(t(as.matrix(df_results_train)),ylim=c(0,0.4),beside=TRUE,legend.text=TRUE,main='By position --- Training error')
```

```{r}
barplot(t(as.matrix(df_results_test)),ylim=c(0,0.4),beside=TRUE,legend.text=TRUE,main='By position --- Testing error')
```

## =============================================================================

# Group by teams


# LOGISTIC REGRESSION MODEL:

```{r}
library(readr)
library(MASS)
starters = read_csv('2019-2020_ANNO_games_details_STARTER.csv')
benches = read_csv('2019-2020_ANNO_games_details_BENCH.csv')
starters = subset(starters, select = -c(COMMENT))
starters = na.omit(starters)
starters$WIN = as.numeric(starters$WIN)
starters$Home_team = as.numeric(starters$Home_team)
starters$TEAM_ABBREVIATION = toupper(starters$TEAM_ABBREVIATION)
starters$START_POSITION = toupper(starters$START_POSITION)

#
d_length = dim(starters)[1]
train_index = sample(d_length, d_length/2)
train_starter = starters[train_index,]
test_starter = starters[-train_index,]


# Position -- 8th
X_train = starters[train_index, 9:29]
X_test = starters[-train_index, 9:29]
Y_train = starters[train_index, 30]
Y_test = starters[-train_index, 30]

#
starters_numeric = starters[, 9:30]

```
```{r, warning = FALSE}
# attach(train_starter)
library(dplyr)
set.seed(1)
# team = train_starter %>% group_by(START_POSITION)
team = train_starter %>% group_by(TEAM_ABBREVIATION)

# Fit the models
lm_models = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(fit = glm(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data=., family = binomial(logit)))


#
my_lm <- function(df) {
    fit = glm(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data=df, family = binomial(logit))
    return(fit)
}

lm_preds = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_lm(.), newdata = test_starter))

lm_preds_train = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_lm(.), newdata = train_starter))

#
lm_error_rate_test = rep(0, 30)
for (x in 1:30) {
  lm_pred_list = lm_preds$pred[[x]]
  lm_pred = rep(0, length(lm_pred_list))
  threshold <- 0.5
  lm_pred[lm_pred_list > threshold] = 1
  lm_error_rate_test[x] = mean(lm_pred != test_starter$WIN)
}

#
lm_error_rate_train = rep(0, 30)
for (x in 1:30) {
  lm_pred_list = lm_preds_train$pred[[x]]
  lm_pred = rep(0, length(lm_pred_list))
  threshold <- 0.5
  lm_pred[lm_pred_list > threshold] = 1
  lm_error_rate_train[x] = mean(lm_pred != train_starter$WIN)
}


print(lm_models$TEAM_ABBREVIATION)
print(lm_error_rate_train)
print(lm_error_rate_test)
```
# Random Forest model:

```{r, warning = FALSE}
#
my_rf <- function(df) {
    fit = randomForest(WIN ~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, data = df, mtry = 5, importance=TRUE, ntrees=25)
    return(fit)
}

rf_preds = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_rf(.), newdata = test_starter))

rf_preds_train = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_rf(.), newdata = train_starter))

#
rf_error_rate_test = rep(0, 30)
for (x in 1:30) {
  rf_pred_list = rf_preds$pred[[x]]
  rf_pred = rep(0, length(rf_pred_list))
  threshold <- 0.5
  rf_pred[rf_pred_list > threshold] = 1
  rf_error_rate_test[x] = mean(rf_pred != test_starter$WIN)
}

rf_error_rate_train = rep(0, 30)
for (x in 1:30) {
  rf_pred_list = rf_preds_train$pred[[x]]
  rf_pred = rep(0, length(rf_pred_list))
  threshold <- 0.5
  rf_pred[rf_pred_list > threshold] = 1
  rf_error_rate_train[x] = mean(rf_pred != train_starter$WIN)
}


print(lm_models$TEAM_ABBREVIATION)
print(rf_error_rate_train)
print(rf_error_rate_test)
```


# SVM model:

```{r}
#
my_svm <- function(df) {
    fit = svm(WIN~ MIN + FGM + FGA + FG_PCT + FG3M + FG3A + FG3_PCT + FTM + FTA + FT_PCT + OREB + DREB + REB + AST + STL + BLK + TO + PF + PTS + PLUS_MINUS + Home_team, kernel = "radial", data = df)
    return(fit)
}

svm_preds = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_svm(.), newdata = test_starter))

svm_preds_train = train_starter %>% 
  group_by(TEAM_ABBREVIATION) %>%
  do(pred = predict(my_svm(.), newdata = train_starter))


#
svm_error_rate_test = rep(0, 30)
for (x in 1:30) {
  svm_pred_list = svm_preds$pred[[x]]
  svm_pred = rep(0, length(svm_pred_list))
  threshold <- 0.5
  svm_pred[svm_pred_list > threshold] = 1
  svm_error_rate_test[x] = mean(svm_pred != test_starter$WIN)
}

svm_error_rate_train = rep(0, 30)
for (x in 1:30) {
  svm_pred_list = svm_preds_train$pred[[x]]
  svm_pred = rep(0, length(svm_pred_list))
  threshold <- 0.5
  svm_pred[svm_pred_list > threshold] = 1
  svm_error_rate_train[x] = mean(svm_pred != train_starter$WIN)
}


print(lm_models$TEAM_ABBREVIATION)
print(svm_error_rate_train)
print(svm_error_rate_test)
```


# Print the results
```{r}
df_results_train <- data.frame(svm = svm_error_rate_train, RF = rf_error_rate_train, lm=lm_error_rate_train)
row.names(df_results_train) <- lm_models$TEAM_ABBREVIATION

df_results_test <- data.frame(svm = svm_error_rate_test, RF = rf_error_rate_test, lm=lm_error_rate_test)
row.names(df_results_test) <- lm_models$TEAM_ABBREVIATION

df_results_train
df_results_test
barplot(t(as.matrix(df_results_train)),ylim=c(0,0.6),beside=TRUE,legend.text=TRUE,las=2,main='By team --- Training error',cex.names=1)
```

```{r}
barplot(t(as.matrix(df_results_test)),ylim=c(0,0.6),beside=TRUE,legend.text=TRUE,las=2,main='By team --- Testing error',cex.names=1)
```











